name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: src
        
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies (p7zip)
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake p7zip-full


    - name: Verify 7z installation
      run: 7z

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/Qt
        key: ${{ runner.os }}-QtCache

    - name: Install Qt
      if: steps.cache-qt.outputs.cache-hit != 'true'
      uses: jurplel/install-qt-action@v2
      with:
        dir: ${{ github.workspace }}/Qt
        version: '5.15.2'  # Specify the desired version
        host: 'linux'      # Specify the host platform
        target: 'desktop'
        install-deps: 'true'

    - name: cmake
      run: cmake .

    - name: Build unit tests for BtsApplication
      run: make BtsApplicationUT

    - name: Run BtsApplication unit tests
      run: ./BTS/Tests/Application/BtsApplicationUT

    - name: Build unit tests for COMMON
      run: make COMMON_UT

    - name: Run COMMON unit tests
      run: ./COMMON/Tests/COMMON_UT

    - name: Build unit tests for UeApplication
      run: make UeApplicationUT

    - name: Run UeApplication unit tests
      run: ./UE/Tests/Application/UeApplicationUT

    - name: Build executables UE and BTS
      run: make UE BTS

    

